"""empty message

Revision ID: 530bc995fe6e
Revises: d3a706c1d86a
Create Date: 2022-03-17 15:34:11.023341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530bc995fe6e'
down_revision = 'd3a706c1d86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.String(length=25), nullable=True),
    sa.Column('box_office', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
