"""empty message

Revision ID: b67034f823b9
Revises: 530bc995fe6e
Create Date: 2022-03-17 16:52:51.911574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67034f823b9'
down_revision = '530bc995fe6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('image', sa.String(length=150), nullable=True))
    op.add_column('movies', sa.Column('image', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'image')
    op.drop_column('animal', 'image')
    # ### end Alembic commands ###
